name:                free-introduction
version:             0.1.0.0
github:              "githubuser/free-introduction"
license:             MIT
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/free-introduction#readme>

dependencies:
- base >= 4.7 && < 5
- free
- mtl
- wl-pprint-annotated

library:
  source-dirs: src
